fix padding on feed
jsgram/JSGram pull request #292
Opened 2019-10-12 21:08 UTC by Volodia1999

2019-10-13 21:39 UTC, InnaKutsik requested changes

2019-10-13 21:39 UTC, InnaKutsik commented on client/src/components/Comments/index.tsx
> +                {this.props.allCommentsId && this.props.allCommentsId.map((commentId: any) => (
any?

2019-10-14 08:37 UTC, Volodia1999 commented on client/src/components/Comments/index.tsx
> +                {this.props.allCommentsId && this.props.allCommentsId.map((commentId: any) => (
fixed

2019-10-14 08:47 UTC, anna-kuzii requested changes

2019-10-14 08:47 UTC, anna-kuzii commented on client/src/components/Comments/Comments.test.tsx
> +        expect(renderer.html()).toHaveLength(153);
pls DO NOT CHANGE IT IN EACH PR!!!
Rewrite it

2019-10-14 08:47 UTC, InnaKutsik submitted a review, later dismissed

2019-10-14 08:53 UTC, anna-kuzii approved these changes

2019-10-14 08:59 UTC, yuriimartynenko approved these changes

2019-10-14 09:00 UTC, merged