360 - FE Mentioned Posts
jsgram/JSGram pull request #293
Opened 2019-10-13 16:20 UTC by zennarchi

2019-10-13 21:41 UTC, InnaKutsik requested changes

2019-10-13 21:41 UTC, InnaKutsik commented on client/src/store/mentionList/actions.ts
> +export const getMoreMentionListSuccess = (userNews: any): { type: string, payload: any } => ({
any?

2019-10-14 09:23 UTC, zennarchi commented on client/src/store/mentionList/actions.ts
> +export const getMoreMentionListSuccess = (userNews: any): { type: string, payload: any } => ({
Fixed

2019-10-14 09:47 UTC, InnaKutsik approved these changes

2019-10-14 10:13 UTC, yuriimartynenko approved these changes

2019-10-14 10:14 UTC, merged