bugfix object-jit, wrong password, Jumping through site part #1
jsgram/JSGram pull request #295
Opened 2019-10-14 09:16 UTC by yuriimartynenko

2019-10-14 17:50 UTC, vglfr submitted a review, later dismissed

2019-10-15 09:10 UTC, anna-kuzii requested changes

2019-10-15 09:10 UTC, anna-kuzii commented on server/src/controllers/auth.controllers/test/login.test.ts
> +        expect(passport.authenticate).toHaveBeenCalledTimes(0);
why?

2019-10-15 16:18 UTC, yuriimartynenko commented on server/src/controllers/auth.controllers/test/login.test.ts
> +        expect(passport.authenticate).toHaveBeenCalledTimes(0);
fixed

2019-10-15 16:50 UTC, anna-kuzii approved these changes

2019-10-15 16:58 UTC, RevuraV approved these changes

2019-10-15 16:59 UTC, merged